name = "ragnet-tools"
main = "src/worker.ts"
compatibility_date = "2025-07-31"

[vars]
BOT_TOKEN = "8197335440:AAEY93jyo1P94iJ0rx2xPNb20c6H60BWjvg"

[[kv_namespaces]]
binding = "USERS"
id = "f5dacfe7c86348c2a001d3e666cf1252"
