name = "fb-coin-bot"
main = "src/worker.ts"
compatibility_date = "2024-07-31"

[vars]
BOT_TOKEN = "8197335440:AAEY93jyo1P94iJ0rx2xPNb20c6H60BWjvg"


[[kv_namespaces]]
binding = "STORAGE"
id = "a69129a6db784c65ad2d301964250a0d"   # dari dashboard Cloudflare
